version: 2
updates:
  # We use "/" as the directory, as this repository is managed by npm workspaces,
  # and that's where the package-lock.json is located
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    # The following is required for workspaces to be updated: see https://github.com/dependabot/dependabot-core/issues/5226.
    versioning-strategy: increase
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/eslint-configs/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
