version: 2
updates:
  # We use "/" as the directory, as this repository is managed by npm workspaces,
  # and that's where the package-lock.json is located
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    # The following is required for workspaces to be updated: see https://github.com/dependabot/dependabot-core/issues/5226.
    versioning-strategy: increase
    open-pull-requests-limit: 10
    allow:
    - dependency-type: "all"
    update-type: "all"
    groups:
      external-types:
        patterns:
          - "@types/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "e2e/browser/test-app"
    schedule:
      interval: "weekly"
    groups:
      external-types:
        patterns:
          - "@types/*"
