name: CI

on:
  pull_request:

env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node-version: ["16", "14"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --workspaces
      # Running top-level ci should happen after workspaces level, running these
      # the other way around results in top-level dependencies (namely, lerna)
      # not being installed.
      - run: npm ci
      - run: npm run build
