name: CI

on: [push]

env:
  CI: true
jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      build: true

  build:
    runs-on: ${{ matrix.os }}
    environment:
      name: ${{ matrix.environment-name }}
    strategy:
      fail-fast: true
      matrix:
        environment-name: ["ESS PodSpaces"]
        os: [ubuntu-latest]
        node-version: ["18", "20"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --workspaces
      # Running top-level ci should happen after workspaces level, running these
      # the other way around results in top-level dependencies (namely, lerna)
      # not being installed.
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - run: npm run e2e:test:setup
      - # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
        # We want jobs in this workflow to be gating PRs, so the whole matrix must
        # run even for dependabot so that the matrixed jobs are skipped, instead
        # of the whole pipeline.
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: npm run test
        env:
          E2E_DEMO_CLIENT_APP_URL: http://localhost:3001
          E2E_TEST_USER: ${{ secrets.E2E_TEST_USER }}
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
          E2E_TEST_IDP: ${{ secrets.E2E_TEST_IDP }}
          E2E_TEST_OWNER_CLIENT_ID: ${{ secrets.E2E_TEST_OWNER_CLIENT_ID }}
          E2E_TEST_OWNER_CLIENT_SECRET: ${{ secrets.E2E_TEST_OWNER_CLIENT_SECRET }}
          E2E_TEST_ENVIRONMENT: ${{ matrix.environment-name }}
      - name: Archive browser-based end-to-end test request logs
        uses: actions/upload-artifact@v4
        # if: failure()
        continue-on-error: true
        with:
          name: playwright-output
          path: test-results/
