name: Mock Release

on:
  pull_request:

env:
  CI: true
jobs:
  release-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --workspaces
      - run: npm run build --if-present --workspaces
