# This workflow assumes that that the package being published has a
# pre-publish workflow step as we DO NOT call 'npm run build'
name: Reusable Release Workflow

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true

env:
  CI: true
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare for publication to npm
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm ci
      - if: ${{ contains(github.ref_name, 'beta') }}
        run: npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - if: ${{ contains(github.ref_name, 'alpha') }}
        run: npm publish --access public --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - if: ${{ !contains(github.ref_name, 'alpha') && !contains(github.ref_name, 'beta') }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
